### ISSUE TITLE
Communication with node stalls after `ZWaveError: Security CC requires a nonce to be sent`

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#3811]

**Comment by steve28** [comment]
I am seeing this as well - started happening after I updated to 8.8.2, more specifically zwavejs2mqtt 6.0.2

**Comment by AlCalzone** [comment]
Can you share one of your logs so I can see if the issue is the same?

**Comment by mwav3** [comment]
I also experienced this twice.  Received this error and everything completely locked up and stopped responding in the zwave network until I restarted (running zwavejs2mqtt in docker).  My logs were set to error only at the time so my only entry is the following:

```
2021-11-29T03:01:29.799Z DRIVER   Unexpected error during SerialAPI command: ZWaveError: Security CC requires a 
                                  nonce to be sent! (ZW1400)
                                      at throwNoNonce (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/S
                                  ecurityCC.ts:603:10)
                                      at SecurityCCCommandEncapsulation.serialize (/usr/src/app/node_modules/zwa
                                  ve-js/src/lib/commandclass/SecurityCC.ts:615:23)
                                      at SendDataRequest.serialize (/usr/src/app/node_modules/zwave-js/src/lib/c
                                  ontroller/SendDataMessages.ts:107:37)
                                      at getSerialAPICommandMachineConfig (/usr/src/app/node_modules/zwave-js/sr
                                  c/lib/driver/SerialAPICommandMachine.ts:143:18)
                                      at createSerialAPICommandMachine (/usr/src/app/node_modules/zwave-js/src/l
                                  ib/driver/SerialAPICommandMachine.ts:385:3)
                                      at executeSerialAPICommand (/usr/src/app/node_modules/zwave-js/src/lib/dri
                                  ver/CommandQueueMachine.ts:276:43)
                                      at Interpreter.exec (/usr/src/app/node_modules/xstate/lib/interpreter.js:8
                                  45:61)
                                      at Interpreter.execute (/usr/src/app/node_modules/xstate/lib/interpreter.j
                                  s:204:14)
                                      at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js
                                  :230:12)
                                      at /usr/src/app/node_modules/xstate/lib/interpreter.js:110:15
```

**Comment by AlCalzone** [comment]
Can you try and make a log which captures the communication before that failure (when it happens again)? I wonder if it is the same thing I've seen.

**Comment by mwav3** [comment]
Sure, whatever I can do to help. Just set logs to "silly" and will post them if it locks up again.

**Comment by steve28** [comment]
> Can you share one of your logs so I can see if the issue is the same?

Attached the two times it happened to me.  I appended the line number where it occurred to the filename.
[zwavejs_2021-11-29_line_1103.log](https://github.com/zwave-js/node-zwave-js/files/7635083/zwavejs_2021-11-29_line_1103.log)
[zwavejs_2021-11-30_line_561.log](https://github.com/zwave-js/node-zwave-js/files/7635084/zwavejs_2021-11-30_line_561.log)

**Comment by Nixon506E** [comment]
I am seeing this same error and lots of `[Security2CCMessageEncapsulation] [INVALID] error: Duplicate command`

[zwavejs_2021-11-28.log](https://github.com/zwave-js/node-zwave-js/files/7635422/zwavejs_2021-11-28.log)

**Comment by AlCalzone** [comment]
@steve28 the loglevel must be set to debug or I won't see anything relevant.

**Comment by AlCalzone** [comment]
@Nixon506E You seem to have a huuuuuge issue with routing/connectivity.

One culprit Node 77 which tries really hard to send its reports to the controller, for example look at the range `2021-11-28T21:19:18.352Z` to `2021-11-28T21:19:24.122Z`. That's just 6 seconds but like 50 messages from the node, even falling back to broadcasts as a last measure. The outgoing tommand to Node 77 which was just sent prior takes a whopping 25 seconds to reach the target:
```
2021-11-28T21:19:27.523Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            82
                                    transmit status:        OK, took 25390 ms
                                    repeater node IDs:      118, 92
                                    routing attempts:       28
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    ACK RSSI:               -68 dBm
                                    ACK RSSI on repeaters:  -62 dBm, -69 dBm
                                    ACK channel no.:        1
                                    TX channel no.:         1
                                    route failed here:      61 -> 77
```

Meanwhile Node 169 is waiting for a response to a supervision request, but Node 77 keeps spamming so long that other nodes start requesting responses and get impatient, resending their commands:
```
2021-11-28T21:19:38.890Z DRIVER « [Node 169] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -83 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
...

2021-11-28T21:19:59.260Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 72
                                    └─[SupervisionCCGet]
                                      │ session id:      33
                                      │ request updates: false
                                      └─[MultilevelSensorCCReport]
                                          type:  Air temperature
                                          scale: Fahrenheit
                                          value: 64.2
2021-11-28T21:19:59.608Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:19:59.608Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:19:59.966Z SERIAL « 0x012100a80001ac189f034800ac2302d112308e017b0dd1540812b79f1fe019910 (35 bytes)
                                  0bbeb
2021-11-28T21:19:59.967Z DRIVER   Dropping message with invalid payload
2021-11-28T21:19:59.967Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
```

etc. This makes your network so busy that the outgoing request from earlier (which needs to be completed before the driver can even start responding to the others) fails after almost **52 seconds and 23 attempts**:
```
2021-11-28T21:20:20.198Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            83
                                    transmit status:        NoAck, took 51790 ms
                                    routing attempts:       23
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    TX channel no.:         1
                                    route failed here:      120 -> 118
                                    TX power:               0 dBm
                                    measured noise floor:   0 dBm
```
after which the next command to node 173 in direct range is done within 10 milliseconds. This amount of routing is excessive, but I'm not sure where you can reduce it. zwave-js doesn't have the command to change it implemented yet.

---

Note to self - the issue is somewhere in this section where the SPAN state gets reset while the message is in flight, gets retried and the retry fails to serialize:
```
2021-11-28T21:20:20.276Z DRIVER » [Node 172] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ route:            0, 0, 0, 0
                                  │ callback id:      86
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 37
                                    └─[SupervisionCCReport]
                                        session id:          33
                                        more updates follow: false
                                        status:              Success
                                        duration:            0s
2021-11-28T21:20:20.284Z SERIAL « [ACK]                                                                   (0x06)
2021-11-28T21:20:20.285Z SERIAL « 0x010401a90152                                                       (6 bytes)
2021-11-28T21:20:20.285Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:20.285Z DRIVER « [RES] [SendDataBridge]
                                    was sent: true
2021-11-28T21:20:22.015Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200adbd  (32 bytes)
2021-11-28T21:20:22.016Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:22.016Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -83 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:22.017Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:22.101Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200abbb  (32 bytes)
2021-11-28T21:20:22.102Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:22.102Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -85 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:22.102Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:22.152Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200acbc  (32 bytes)
2021-11-28T21:20:22.153Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:22.153Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -84 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:22.153Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:26.942Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200b3a3  (32 bytes)
2021-11-28T21:20:26.943Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:26.943Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:26.944Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.029Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200b2a2  (32 bytes)
2021-11-28T21:20:27.030Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.030Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -78 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.030Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.080Z SERIAL « 0x011e00a80001ac159f0349003503379aba46c2418303a2cd800823a63200b3a3  (32 bytes)
2021-11-28T21:20:27.081Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.081Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -77 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.081Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.414Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2418303a2cd800823a63200e0e4  (32 bytes)
2021-11-28T21:20:27.415Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.415Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -32 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.415Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.461Z SERIAL « 0x012100a80001ac189f034a00c1306fe79c4f83ff99b21b799d2e11e0c2b3d30c0 (35 bytes)
                                  0bbdd
2021-11-28T21:20:27.474Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.474Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Security2CC_CannotDecode
2021-11-28T21:20:27.475Z CNTRLR » [Node 172] Message authentication failed, cannot decode command. Requesting a 
                                  nonce...
2021-11-28T21:20:27.512Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2498303a2cd800023a63200ddd9  (32 bytes)
2021-11-28T21:20:27.513Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.514Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -35 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Security2CC_NoSPAN
2021-11-28T21:20:27.514Z CNTRLR   [Node 172] No SPAN is established yet, cannot decode command.
2021-11-28T21:20:27.651Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2418303a2cd800823a63200d5d1  (32 bytes)
2021-11-28T21:20:27.652Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.652Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -43 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.652Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.687Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2418303a2cd800823a63200d5d1  (32 bytes)
2021-11-28T21:20:27.688Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.688Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -43 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.688Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.756Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2418303a2cd800823a63200eaee  (32 bytes)
2021-11-28T21:20:27.757Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.757Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -22 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.757Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:27.885Z SERIAL « 0x011e00a81401ac159f0349003503379aba46c2418303a2cd800823a63200d9dd  (32 bytes)
2021-11-28T21:20:27.886Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:27.886Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ type:        broadcast
                                  │ target node: 255
                                  │ RSSI:        -39 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:27.886Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:29.049Z SERIAL « 0x012100a80001ac189f034a00c1306fe79c4f83ff99b21b799d2e11e0c2b3d30c0 (35 bytes)
                                  0bbdd
2021-11-28T21:20:29.049Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:29.050Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Security2CC_NoSPAN
2021-11-28T21:20:29.050Z CNTRLR   [Node 172] No SPAN is established yet, cannot decode command.
2021-11-28T21:20:29.538Z SERIAL « 0x012100a80001ac189f034a00c1306fe79c4f83ff99b21b799d2e11e0c2b3d30c0 (35 bytes)
                                  0bbdd
2021-11-28T21:20:29.539Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:29.539Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -69 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:29.539Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:47.074Z SERIAL « 0x012100a80001ac189f034a00c1306fe79c4f83ff99b21b799d2e11e0c2b3d30c0 (35 bytes)
                                  0b9df
2021-11-28T21:20:47.075Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:47.075Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -71 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:47.075Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:47.682Z SERIAL « 0x012100a80001ac189f034a00c1306fe79c4f83ff99b21b799d2e11e0c2b3d30c0 (35 bytes)
                                  0b9df
2021-11-28T21:20:47.682Z DRIVER   Dropping message with invalid payload
2021-11-28T21:20:47.683Z DRIVER « [Node 172] [REQ] [BridgeApplicationCommand]
                                  │ RSSI: -71 dBm
                                  └─[Security2CCMessageEncapsulation] [INVALID]
                                      error: Duplicate command
2021-11-28T21:20:47.683Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:49.657Z SERIAL « 0x011d00a956010b48007f7f7f7f7f01010700000000021ab09000000000001f    (31 bytes)
2021-11-28T21:20:49.658Z SERIAL » [ACK]                                                                   (0x06)
2021-11-28T21:20:49.658Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            86
                                    transmit status:        NoAck, took 28880 ms
                                    routing attempts:       26
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    TX channel no.:         1
                                    route failed here:      176 -> 144
                                    TX power:               0 dBm
                                    measured noise floor:   0 dBm
2021-11-28T21:20:49.739Z DRIVER   Unexpected error during SerialAPI command: ZWaveError: Security S2 CC requires
                                   the receiver's nonce to be sent! (ZW1401)
                                      at Security2CCMessageEncapsulation.serialize (/usr/src/app/node_modules/zw
                                  ave-js/src/lib/commandclass/Security2CC.ts:913:10)
                                      at SendDataBridgeRequest.serialize (/usr/src/app/node_modules/zwave-js/src
                                  /lib/controller/SendDataBridgeMessages.ts:125:37)
                                      at getSerialAPICommandMachineConfig (/usr/src/app/node_modules/zwave-js/sr
                                  c/lib/driver/SerialAPICommandMachine.ts:143:18)
                                      at createSerialAPICommandMachine (/usr/src/app/node_modules/zwave-js/src/l
                                  ib/driver/SerialAPICommandMachine.ts:385:3)
                                      at executeSerialAPICommand (/usr/src/app/node_modules/zwave-js/src/lib/dri
                                  ver/CommandQueueMachine.ts:276:43)
                                      at Interpreter.exec (/usr/src/app/node_modules/xstate/lib/interpreter.js:8
                                  45:61)
                                      at Interpreter.execute (/usr/src/app/node_modules/xstate/lib/interpreter.j
                                  s:204:14)
                                      at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js
                                  :230:12)
                                      at /usr/src/app/node_modules/xstate/lib/interpreter.js:110:15
                                      at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:69
                                  :7)
```

**Comment by AlCalzone** [comment]
@Nixon506E You should your network. Not all at once, that is probably going to end in much larger chaos, but individual nodes.

I'd start by searching for `route failed here` and heal the nodes that are mentioned there (on both ends of the broken link). The next step would be `transmit status:        NoAck`, but this is a bit more tricky.
From these entries you can search upwards for `callback id:` and check if the number behind that is the same as the NoAck message. This should give you some more nodes.

I'm going to add some more tools for this insight in the future so you don't need logs, but they aren't there yet.

**Comment by Nixon506E** [comment]
I knew that node was potentially on the outer limit of the network and it is housed in an old construction wall that is limiting signal to it.

I will try to heal the problem nodes as you mentioned and check for successful transmissions.

Would it be beneficial to add more repeater nodes around this one? Any other reasons this node might be causing problems like this? Should it get replaced?

**Comment by AlCalzone** [comment]
> Would it be beneficial to add more repeater nodes around this one? Any other reasons this node might be causing problems like this? Should it get replaced?

It might help to add 1-2 repeaters between the node and others. From the log it seems like the normal messages reach the controller just fine (although they might be delayed too) but the acknowledgements (which are very short and easily get scrambled) don't reach node 77 reliably and the existing routes aren't consistent.

**Comment by AlCalzone** [comment]
@Nixon506E https://github.com/zwave-js/node-zwave-js/issues/3810 might be related. Your network seems pretty large too, and I guess you're using a 700-series stick?

**Comment by Nixon506E** [comment]
@AlCalzone I am, the zooz model. I did see that issue, definitely could be part of it, it looks like some of the neighbors referenced in the route failed calls are old ones that were removed though so hoping it is more an issue with just needing to be healed to update neighbors

**Comment by mwav3** [comment]
Got the issue to happen again.  I ran the "goodnight" routine that shuts off multiple devices and locks 3 doors.  I have about 22 devices.  I get the error and then everything in the network jams up and becomes unresponsive, and restarting zwavejs2mqtt is the only way to recover it.  Here's the logs, let me know if you need anything else.

[zwavejs_2021-12-01.log](https://github.com/zwave-js/node-zwave-js/files/7637379/zwavejs_2021-12-01.log)

**Comment by Nixon506E** [comment]
Issues on my side still. I put a few smart plugs around the problem node and healed nodes individually until they were all consistently returning successful heal responses. It seems to have cleared up the route failed messages for the problem node but a different node that is now the farthest from other nodes is the one showing the most failed routes, and usually going to it.

Not sure if the new node is the issue or if it is still something else but I again had the controller not able to transmit during the day today and had to reboot. I will try to get some more smart plugs for around the new problem node and see if I can at least stabilize the network. Feels like if the issue is with having a large network then I may be going in the wrong direction...

**Comment by AlCalzone** [comment]
@Nixon506E if you can make another log showing this behavior, I can take a look if your issue is still network related.

**Comment by Nixon506E** [comment]
@AlCalzone I added another node near the new trouble node just now and upgraded to 8.8.3. I'll post new logs if I am still seeing the issue after all of that. Thanks!

**Comment by AlCalzone** [comment]
Note to self: The cause of failure seems to be slightly different for S0 encapsulation. Here, the issue is that a retried security-encapsulated message gets serialized multiple times, but after the first time, the nonce has been consumed.

**Comment by AlCalzone** [comment]
Should be fixed on master

**Comment by Colorado4Wheeler** [comment]
I can confirm that this exact issue is still occurring.  I've been debugging this all week trying to determine if it's software that I needed to open a ticket on or not.  My issue is exactly the same as @mwav3 where I "goodnight" my house and part of that script is to lock the doors and one of the doors throws this error and locks up the entire system.  Z-Wave JS still "works" because I can see motion sensors triggering in HA and in the logs, but no wired device will respond.  The fix is to restart the Z-Wave JS to MQTT add-on and everything returns to normal again.

```
zwavejs2mqtt: 6.1.1
zwave-js: 8.9.0-beta.1
home id: 3823806645
home hex: 0xe3eaa8b5
```

```
2021-12-22T07:00:31.091Z DRIVER   Unexpected error during SerialAPI command: ZWaveError: Security CC requires a 
                                  nonce to be sent! Reason: nonce 0xd8 not found (ZW1400)
                                      at throwNoNonce (/opt/node_modules/zwave-js/src/lib/commandclass/SecurityC
                                  C.ts:83:8)
                                      at SecurityCCCommandEncapsulation.get receiverNonce [as receiverNonce] (/o
                                  pt/node_modules/zwave-js/src/lib/commandclass/SecurityCC.ts:596:4)
                                      at SecurityCCCommandEncapsulation.serialize (/opt/node_modules/zwave-js/sr
                                  c/lib/commandclass/SecurityCC.ts:644:30)
                                      at SendDataRequest.serialize (/opt/node_modules/zwave-js/src/lib/controlle
                                  r/SendDataMessages.ts:107:37)
                                      at getSerialAPICommandMachineConfig (/opt/node_modules/zwave-js/src/lib/dr
                                  iver/SerialAPICommandMachine.ts:143:18)
                                      at createSerialAPICommandMachine (/opt/node_modules/zwave-js/src/lib/drive
                                  r/SerialAPICommandMachine.ts:385:3)
                                      at executeSerialAPICommand (/opt/node_modules/zwave-js/src/lib/driver/Comm
                                  andQueueMachine.ts:276:43)
                                      at Interpreter.exec (/opt/node_modules/xstate/lib/interpreter.js:845:61)
                                      at Interpreter.execute (/opt/node_modules/xstate/lib/interpreter.js:204:14
                                  )
                                      at Interpreter.update (/opt/node_modules/xstate/lib/interpreter.js:230:12)
```

**Comment by AlCalzone** [comment]
> I can confirm that this exact issue is still occurring

Yeah because it is only fixed in beta.3 
You're on beta.1

**Comment by Colorado4Wheeler** [comment]
Got it, thank you!  I was trying to pinpoint when the fix released and couldn't, I appreciate the response!
