### ISSUE TITLE
Second Thermostat Setpoint not being found for Intermatic PE653 z-wave pool controller

### ISSUE THREAD

**Issue by bluemantwo** [AlCalzone/node-zwave-js#5335]
Is your problem within Home Assistant (Core or Z-Wave JS Integration)?
NO, my problem is NOT within Home Assistant or the ZWave JS integration

Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?
NO, my problem is NOT within Z-Wave JS UI

Checklist
 I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is not described there.

 I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was not mentioned there.

Describe the bug

I have an Intermatic PE653 pool controller.  Product Manufacturer: 0x0005, Product Identifiers: 0x5045:0x0653 

I had it included on my ISY944i and was able to access both Thermostat setpoints: one for the Pool which was Type Heating (Type 1) and one for the spa which was Type Furnace (Type 7).  When I included the device in my Home Assistant zwave-js, it only finds the 1 setpoint for Heating.  Attached is the log created by doing a re-interview of the device (Device ID 19).  Inclusion starts at 1:45:36 Zulu in the log.  It seem to not make any reference to the other setpoint.  Any ideas?  My PE653 is running firmware v39.

From Manufacturer: 

`The THERMOSTAT_SETPOINT command Class is fully supported as documented in the Z-Wave Command
Class Specification for support setpoint types HEATING # 1 (setpoint type 1) and FURNACE (setpoint type
#7). The remaining setpoint types are unsupported. The HEATING #1 setpoint is used for setting the POOL
target temperature and the FURNACE setpoint is used for setting the SPA target temperature. `

[zwavejs_2023-01-15.log](https://github.com/zwave-js/node-zwave-js/files/10422003/zwavejs_2023-01-15.log)

Also, if it helps, here is a SmartThings device handler that works with both setpoints:

[intermatic-pe653-pool-control-system.groovy.txt](https://github.com/zwave-js/node-zwave-js/files/10468559/intermatic-pe653-pool-control-system.groovy.txt)

**Comment by AlCalzone** [comment]
I'm afraid they do in fact not implement the Command Class specification correctly. Granted, there was so much confusion around the setpoints in earlier versions that the specifications explicitly call this out and mention how to deal with the two possible interpretations, but the information returned by the device matches neither.

![grafik](https://user-images.githubusercontent.com/17641229/215605429-2085711f-b86c-4306-851b-bfcb781e30bf.png)

In this table, `1.2` means first byte (1-based), bit 2 (0-based). The device returns a value of `0x43` for the first byte, which is `0100 0011` in binary. Acoording to the table, this corresponds to either of these setpoints:
a) N/A, Heating, Auto Changeover (this is what zwave-js makes of this)
b) N/A, Heating, N/A

I think the return value is shifted by one bit from what it was supposed to be (`0x86 = 1000 0110`), which would correspond to these setpoints:
- Heating, Cooling, Furnace.

---

Oh and FWIW, the reason devices like this work in some other systems is because they hardcoded support (sometimes overriding bugs), where Z-Wave JS relies on discovering functionality through the Z-Wave standard.

**Comment by bluemantwo** [comment]
@AlCalzone , thanks for the great and helpful reply.  The odd thing is that the ISY this device was connected to had no support at all for the PE653.  It just happened to work.  Also odd is that while Intermatic goes out of their way to say that setpoint 2 is Furnace, it showed up as Cooling in the ISY.  They definitely messed something up.  Your idea that they shifted the return value by 1 bit does seem very plausible.  

I am sort of new to this, but is there a way I can write a custom driver that would adjust for this? It is such a 'one off' product (doubt there are more than 1000 or so in the wild with my v3.9 firmware) that I might have to just do this one myself somehow (?)

Oh, and shouldn't this really be Cooling, Heating, Autochangeover or else Furnace, Heating, Autochangeover?

**Comment by kpine** [comment]
FYI, there's already an issue for this, https://github.com/zwave-js/node-zwave-js/issues/4588, along with a POC PR to allow for overriding the auto-detected setpoints.

@AlCalzone why don't the interview logs here show the setpoint interpretation selection since the CC is v1? I see the logs on my v2 (`"Thermostat Setpoint bitmap interpretation is unknown, assuming B for now"`). Not that it would help here, just curious.

@bluemantwo You can try manually programming setpoint 7 with a HA Dev Tools Service call:

```yaml
service: zwave_js.invoke_cc_api
data:
  command_class: "67"  # thermostat setpoint cc
  method_name: set
  endpoint: "1"
  parameters:
    - 7   # setpoint
    - 78  # temperature
    - 1   # scale: 1 == F
target:
  entity_id: climate.z_wave_thermostat
```

In my testing, Z-Wave JS does not care whether the setpoints are supported or not, it will just do as you say. You will not be able to view the setpoint values in HA.

As an aside, seems like your ZUI's device DB is corrupted. Might want to get the fixed somehow. No idea how to do that if this is the HAOS add-on.

```text
2023-01-16T01:42:26.630Z CONFIG   version 10.3.1
2023-01-16T01:42:27.862Z CONFIG   Error parsing config file dsb09.json: Could not parse config file /data/store/
                                  config/templates/aeotec_template.json: ENOENT: no such file or directory, open
                                   '/data/store/config/templates/aeotec_template.json'
                                  Import stack: 
                                    in #selective_reporting
                                    in /data/store/config/dsb09.json (ZW0340)
```

**Comment by bluemantwo** [comment]
@kpine You did it!!!!!  All I really need is the ability to set the Furnace Setpoint, and using the service call you listed, it worked!!!  I did have to use endpoint 0 (as opposed to 1), but it worked!!!!!

It would also be nice, though not critical, to be able to also read the setpoint value for Furnace (7).  Is there a way to set a variable to that value by doing a 'get' type of command?  

THANK YOU!!!!!!!

**Comment by kpine** [comment]
> I did have to use endpoint 0 (as opposed to 1), but it worked!!!!!

Weird, I only picked 1 because most of the logs were for endpoint 1.

> It would also be nice, though not critical, to be able to also read the setpoint value for Furnace (7). Is there a way to set a variable to that value by doing a 'get' type of command?

You can just change the service call to do a get:

```text
service: zwave_js.invoke_cc_api
data:
  command_class: "67"  # thermostat setpoint cc
  method_name: get
  parameters:
    - 7   # setpoint
target:
  entity_id: climate.z_wave_thermostat
```

However, I think all you can do with that is look in the logs for the result. It won't show up in HA, at least not permanently.

**Comment by bluemantwo** [comment]
@kpine , you freaking genius!!!!!  I just realized that after doing the call to set and then get the value for the Setpoint that was not showing up, it now shows up with an entity id in Home Assistant!!!!!!!  

![image](https://user-images.githubusercontent.com/22325437/215668314-a72c96c6-7464-455c-b18a-bd2e038702e0.png)

We can close this item out.

**Comment by kpine** [comment]
If you restart ZUI, you may see that the entity goes unavailable. Seems like that can be worked around with some occasional polling.

**Comment by bluemantwo** [comment]
I just did a power down of the entire system, rebooted, and the entity still is there.  I then did a re-interview of the device, and that wiped it. But as soon as I ran the 'get' script it was back.  

However, I did notice now that it really does not help.  2 entities are created, one for Heat and one for Furnace.  Each one does write successfully to the pool controller.  However, when using the entities created by HA, both appear to be talking to the Heat device.  The  Furnace device is no good.  Also, if I do a refresh of the values in the ZUI console (clicking on the refresh box as you can see in my picture above), it only refreshes Heat.  Looking at the log, it only queries Heat (1) and not Furnace (7).  Very odd.  The system definitely sees both, but remains confused thinking the second entity is the same as the first.  

Nevertheless, I can still use a "set" automation triggered by an input_number entity to create a slider to set the temperature.  That is all I need.  And that definitely works.  

Nice!

**Comment by AlCalzone** [comment]
> why don't the interview logs here show the setpoint interpretation selection since the CC is v1?

Probably because the endpoints are set up differently for Multi Channel CC v1 and that information is lost in translation.

**Comment by bluemantwo** [comment]
@kpine  , I had a follow up question related to the Clock setting on my pool controller.  I am not able to read or set the clock for time of day.  It tends to gain about 30 seconds per day so much be reset regularly.  Right now I have to do it using the z-wave remote control that came with the system.  I would like to be able to set it automatically from Home Assistant.  The attached log shows that the Clock is discovered (command class 0x81/129) and during discovery it does seem to report its current time, but when I try to issue a clock set or get command, I see nothing in the logs in terms of response from the pool controller.  

This is the command I am sending it (sorry, but formatting for spacing gets lost when I post here):

service: zwave_js.invoke_cc_api
data:
  method_name: get
  endpoint: "1"
  command_class: "129"
  parameters:
    - 1
target:
  device_id: dea02e849740113a6c5c426a9b4d5eb1

I was not sure what parameter to use and could not find any documentation on parameters with a Clock. I also tried endpoint 0 with no joy either.  Any thoughts on what else I might try?  
[Pool Node Interview Log.txt](https://github.com/zwave-js/node-zwave-js/files/11183623/Pool.Node.Interview.Log.txt)

**Comment by bluemantwo** [comment]
Well, hell.  @kpine  , just putting my thoughts together to ask you the question allowed me to figure it out!  I decided rather than doing a get, I would do a set, with parameters hours and minutes.  And sure enough, it works!  It set the clock!  Sorry for bothering you, but thanks for being a sounding board to help me get my thoughts in order.  

Here is the command that works:

service: zwave_js.invoke_cc_api
data:
  method_name: set
  command_class: "129"
  parameters:
    - 10
    - 09
target:
  device_id: dea02e849740113a6c5c426a9b4d5eb1

That sets clock to 10:09am.  Yay!!!

Not sure why 'get' does not do anything, but that is not what I needed anyway.  I was just using 'get' as a way to test if I am really talking to the clock.

**Comment by bluemantwo** [comment]
Sorry, @kpine , I accidently tagged the above 2 items to AlCalzone.  I updated them to direct the to you.  Problem is now solved, but I wanted to make sure you knew I appreciated your earlier directions which helped me solve it!

**Comment by kpine** [comment]
[`ClockCC.get()`](https://zwave-js.github.io/node-zwave-js/#/api/CCs/Clock?id=get) doesn't have any parameters, not sure if they are just ignored or if that's causing an error. I can see the interview does a get and succeeds. It's also using endpoint 0, not 1. Then the service should be:

```yaml
service: zwave_js.invoke_cc_api
data:
  command_class: "129"
  method_name: get
  parameters: []
target:
  device_id: dea02e849740113a6c5c426a9b4d5eb1
```

You also won't get any kind of response in HA, you'll have to look at the driver logs to see the result. Doesn't seem useful then, so just updating the clock on an interval sounds like the right approach.

**Comment by AlCalzone** [comment]
maybe this api is simpler?
https://zwave-js.github.io/node-zwave-js/#/api/node?id=setdateandtime

**Comment by bluemantwo** [comment]
> maybe this api is simpler? https://zwave-js.github.io/node-zwave-js/#/api/node?id=setdateandtime

I will give that a try.  I did see that in my searches, but was unsure if my super old device would support it.  Thanks @AlCalzone for this and all the help you have provided.  You and kpine have allowed me to make my z-wave setup much better.  The heat setpoint issue and this clock issue were driving me crazy for several years but you guys helped solve them both.  That is what makes Home Assistant community so great.

**Comment by AlCalzone** [comment]
That API is specifically built to support all possible time related CCs a device may use.

**Comment by JDogg016** [comment]
Ok.  This thread is way beyond my intelligence level.  I have FW 3.4 installed and have 5 switches, an air temperature sensor and a number entity (basic) available.

I am looking to discover the thermostat entity and possibly control my variable speed pool pump and I find it very interesting that you are writing service calls into HA to control some entities that may not otherwise be exposed.

Any assistant you can lend would be great as I could then use Node Red to build automations.

**Comment by AlCalzone** [comment]
@bluemantwo #6044 should fix this issue by overriding the setpoint query with the correct values. I'm unable to test though due to not having the device.
When 11.5.3 lands in the application you're using, can you re-interview the device and see if that fixes the setpoints?

**Comment by bluemantwo** [comment]
I will do.  Thank you so much for the exceptional work you are doing for the community.

**Comment by bluemantwo** [comment]
@AlCalzone , 11.5.3 did not seem to resolve the issue for the second thermostat setpoint.  To recap, there are 2 setptoints.  Setpoint 1 (heating, for pool) and setpoint 7 (furnace, for spa).  I did a re-interview (log attached) and it found Setpoint 1 as always, but not setpoint 7.  

However, since I can do a custom call to the specific address of Setpoint 7 to read and write the data, I do not consider this a serious issue.  OK to mark closed in my view.  And thank you so much for all you are doing for z-wave.  It is amazingly great now.  
[PE653 interview log.txt](https://github.com/zwave-js/node-zwave-js/files/12138007/PE653.interview.log.txt)

**Comment by AlCalzone** [comment]
@bluemantwo unfortunately that log is of no help. I need a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs) on loglevel **debug**.
I'd still like to fix this, since the device seems somewhat popular and reducing friction here is good.

**Comment by bluemantwo** [comment]
EDIT: I need to learn to read.  I see you requested DRIVER LOG.  I will do that.  

I own 2 of these devices.  One running the more prevalent 3.4 firmware, which is what most users are on, which I have just as a spare and do not use.  The other is running 3.9 firmware, which is a special firmware developed by Intermatic for property managers which has (supposedly) improved z-wave compliance.  Version 3.9 is the one I am using. 

The reason I am reluctant to have you or anyone spend much time on this device is that the volumes are low, and then there are 3 firmware versions used: 3.3 (20% of users), 3.4 (70% of users), and 3.9 (just a handful).   All those permutations and the fact that Intermatic did not follow z-wave standards at all, makes this device a PITA to support.  

As for the thermostats (Heater-1 and Furnace-7), I am not even sure they are handled the same way across firmwares.  

So these devices kind of belong in the category of "better than nothing" support.  ;)

**Comment by bluemantwo** [comment]
@AlCalzone , here is the detailed log for the interview of the PE653.  Node 19.  
[PE653 interview (Node 19).txt](https://github.com/zwave-js/node-zwave-js/files/12176001/PE653.interview.Node.19.txt)

It appears the other setpoint which should be 0x07 (furnace, which is for the Spa) is being seen as 0x06, which is not used.  That may be the problem. 

Thanks for looking into this.

**Comment by AlCalzone** [comment]
Hmm I think this is a combination of a handful of semi-related issues:
1. I suspect that firmware 3.9 also only supports Multi Channel CC v1, but it reports support for V2 like firmware 3.4 where we forced the use of v1. As a result a lot of queries for the endpoints fail.
2. Your device seems to have bad connectivity. I see several communication attempts falling back to 9.6 kbit/s and many RSSI readings below -90 dBm which is terribly close to background noise.
3. Lots of responses to endpoint functionality queries are delayed and/or repeated (probably due to the above), and Z-Wave JS currently fails to check that the received one matches the queried one, so there is a bit of chaos in the interview (which also fails a couple of times).

I suspect these problems are also the reason why the compat flag does not get applied. We shouldn't actually see the thermostat setpoint query go out, but it does.

You'll need to look into 2., I'll have to fix 1. and 3. before we can retry.

**Comment by bluemantwo** [comment]
Yes, 2. is probably correct and understandable.  It is quite a distance from my indoor z-wave controller and the outdoor pool house where the pool controller is.  Pool controller is also one of the few 300 series devices left on my network, if that matters.  I have a z-wave repeater mid way between the z-wave controller and pool controller, but for some reason it always wants to go direct.

**Comment by AlCalzone** [comment]
> but for some reason it always wants to go direct

The latest Z-Wave JS UI lets you configure priority (return) routes which are always attempted first.

**Comment by AlCalzone** [comment]
@bluemantwo did you manage to improve the connectivity? Problems 1 and 3 above are fixed, so we should be able to continue.

**Comment by bluemantwo** [comment]
@AlCalzone , do you recall which release has the latest fix for this?  I will make sure I am updated and try today.  Thanks as always.

**Comment by AlCalzone** [comment]
Driver version `11.7.0`, which should be included in all latest addon/application versions

**Comment by bluemantwo** [comment]
@AlCalzone , still no luck finding the second thermostat setpoint.  Currently running 11.13.0.  Log attached.  
[Node 19 Thermostat.log](https://github.com/zwave-js/node-zwave-js/files/12434128/Node.19.Thermostat.log)

**Comment by AlCalzone** [comment]
I think this is the problem:
> 2023-08-24T23:34:59.165Z CNTRLR   [Node 019] User-provided device config loaded

You still have an old custom config file which gets preferred over the one we're trying to test.

**Comment by bluemantwo** [comment]
DOH!!!!!!  Let me remove that and give it a try.  Maybe the problem for the past several attempts.

**Comment by bluemantwo** [comment]
@AlCalzone, I am an idiot.  It works perfectly.  I had written my own custom parameter definitions for firmware v39 which is why I had a custom file.   I have to still look, but it appears the new version is giving me all of the custom parameters I needed (and more!).   This broke some of my old settings and automations, but I will fix those to adjust to your new config file.  

THANKS so much for your work on this.

and SORRY for forgetting I was using a custom config file.  Really sorry for that as it probably wasted your time on some of these issues. 

 YAY!!!!!!!!

**Comment by bluemantwo** [comment]
@AlCalzone , just another follow up.  Everything is working 100% for me on firmware v3.9.  I can finally drop that custom config file I had been using.  This is just perfect!!!

**Comment by bluemantwo** [comment]
@AlCalzone ,

Still one issue with the thermostat after all, which I did not realize until now.  While both the setpoints now show up as entities in the HA UI, the Furnace/Spa setpoint does not work.  The Heat/Pool entity also controls the Heater/Pool setpoint just fine.  I did not realize because I use a script that sends commands directly to it which works fine.  

BUT, good news is that from the JS-UI interface under Thermostat setpoints, I CAN control both setpoints correctly.  SO the issue may just be with the Entity not being written correctly.  I included new log, which includes this comment at the end:

2023-08-26T17:44:37.195Z CNTRLR   [Node 019] Interviewing Thermostat Setpoint...
2023-08-26T17:44:37.195Z CNTRLR » [Node 019] retrieving supported setpoint types...
2023-08-26T17:44:37.196Z CNTRLR   [Node 019] Thermostat Setpoint bitmap interpretation is unknown, assuming B fo
                                  r now
2023-08-26T17:44:37.196Z CNTRLR » [Node 019] querying current value of setpoint Heating...
2023-08-26T17:44:37.337Z CNTRLR « [Node 019] received current value of setpoint Heating: 39 °F
2023-08-26T17:44:37.337Z CNTRLR » [Node 019] querying current value of setpoint Furnace...
2023-08-26T17:44:37.478Z CNTRLR « [Node 019] received current value of setpoint Furnace: 39 °F

Don't take any action on this yet, I just wanted to let you know.  I will do some more investigation today and get back to you.  Thanks as always!!!

**Comment by bluemantwo** [comment]
More follow up.  Picture below shows that the settings in the JS-UI interface work perfectly for both pool (heater) and spa (furnace).  In the past, only pool was working.  I can set the spa setpoint, and it shows up in my pool system as having changed to the correct value.  I can also change the value from my pool system, and do a refresh in the js-ui and it reads correctly. 

However, the entity created for spa climate does not allow changing the spa setpoint.  Pool works fine.  
![jsue](https://github.com/zwave-js/node-zwave-js/assets/22325437/9d99c42b-9693-4231-87ee-06631212a840)

**Comment by AlCalzone** [comment]
> However, the entity created for spa climate does not allow changing the spa setpoint. Pool works fine.

I'm a bit tired, so I'm not 100% sure I understood you:
- In Z-Wave JS UI, both setpoints work
- In Home Assistant itself, only one of the setpoint works

Correct?

**Comment by bluemantwo** [comment]
Yes.  In the picture above, in the JS UI, I am able to read and write both setpoints.  Verified they work by using hand control (PE953) to confirm settings.  

But in HA, the SPA setting does not work.    See screen shot below.  Spa does not show setpoint value and when you try to change it give the error message shown at the bottom below.

![setpoints](https://github.com/zwave-js/node-zwave-js/assets/22325437/255eb0b4-8893-4ccd-bed2-f5162a0c9c41)

**Comment by AlCalzone** [comment]
@marcelveldt, this might be another case for you :) I've seen this error before on climate entities.

**Comment by bluemantwo** [comment]
I really appreciate the work of whoever created all the parameter values for the PE653.  There were several that I never knew existed, and a couple I had guessed wrong on.  HUGE thanks to whoever did all the research and detective work to get those parameters.  My experience has been that Intermatic has been terrible at documenting their pool controller in the past.

**Comment by AlCalzone** [comment]
That would be @philh30 in https://github.com/zwave-js/node-zwave-js/pull/5822
Sorry for the tag, but credit where credit is due :)

**Comment by bluemantwo** [comment]
Thanks @philh30 !!!  You da man! 

And @AlCalzone ,  could the issue with my second setpoint be due to the endpoint being wrong?  This is the put put from diagnostic request done in the HA interface (not JS-UI):

note: Pool_3 with endpoint: 1 works, Pool_2 with endpoint: 0 does not.  Also, when I manually send commands to endpoint 1 for furnace (7) for pool_2, that works fine.  So I am pretty sure this endpoint issue is the problem.  

    "domain": "climate",
        "entity_id": "climate.pool_3",
        "original_name": "",
        "original_device_class": null,
        "disabled": false,
        "disabled_by": null,
        "hidden_by": null,
        "original_icon": null,
        "entity_category": null,
        "supported_features": 1,
        "unit_of_measurement": null,
        "value_id": "19-67-1-setpoint-1",
        "primary_value": {
          "command_class": 67,
          "command_class_name": "Thermostat Setpoint",
          "endpoint": 1,
          "property": "setpoint",
          "property_name": "setpoint",
          "property_key": 1,
          "property_key_name": "Heating"
      
      
      domain": "climate",
              "entity_id": "climate.pool_2",
              "original_name": "",
              "original_device_class": null,
              "disabled": false,
              "disabled_by": null,
              "hidden_by": null,
              "original_icon": null,
              "entity_category": null,
              "supported_features": 1,
              "unit_of_measurement": null,
              "value_id": "19-67-0-setpoint-7",
              "primary_value": {
                "command_class": 67,
                "command_class_name": "Thermostat Setpoint",
                "endpoint": 0,
                "property": "setpoint",
                "property_name": "setpoint",
                "property_key": 7,
          "property_key_name": "Furnace"

**Comment by kpine** [comment]
Please attach the entire device diagnostic, not just the snippets.

**Comment by bluemantwo** [comment]
[zwave_js-3a152d2a5cd6e4dafe5146f53abf5151-Pool-dea02e849740113a6c5c426a9b4d5eb1.json (1).txt](https://github.com/zwave-js/node-zwave-js/files/12458155/zwave_js-3a152d2a5cd6e4dafe5146f53abf5151-Pool-dea02e849740113a6c5c426a9b4d5eb1.json.1.txt)

**Comment by kpine** [comment]
Thanks, not surprisingly this last problem is a bug in HA. Would you mind submitting an issue? https://github.com/home-assistant/core/issues/new/choose

For future reference, when HA sees a thermostat without a mode, it assumes the setpoint only supports heating. I think this has been true for all of these devices seen so far, which have been heating valves (hence the comment). Since you have both Heating and Furnace setpoints, but no mode, HA incorrectly handles the furnace setpoint type, which produces the error you're seeing. https://github.com/home-assistant/core/blob/5ec645161de4d68138a236f2c20b259e8628e59b/homeassistant/components/zwave_js/climate.py#L259-L265

```python
    @property
    def _current_mode_setpoint_enums(self) -> list[ThermostatSetpointType]:
        """Return the list of enums that are relevant to the current thermostat mode."""
        if self._current_mode is None or self._current_mode.value is None:
            # Thermostat(valve) with no support for setting a mode
            # is considered heating-only
            return [ThermostatSetpointType.HEATING]
        return THERMOSTAT_MODE_SETPOINT_MAP.get(int(self._current_mode.value), [])
```

That code should be returning `[ThermostatSetpointType.FURNACE]` for the failing case.

A separate question, are you ignoring the climate entities' current temperature? Due to the endpoints, the integration will only associate the first temperature sensor it finds, which is the same for both (endpoint 2). However, there are 4 sensor values (endpoints 2-5), and HA has no way of picking which corresponds.

**Comment by bluemantwo** [comment]
@kpine , thanks for the follow up.  As to the current temperatures, there is only 1 water temperature probe.   The probe is placed BEFORE the pool/spa diverter valve so that it always gives the temperature of the water that is flowing through the pump.  So that fact that both setpoints will use the same current temperature works perfectly.  

I will submit the issue in the next day or so.

**Comment by AlCalzone** [comment]
Closing as this is solved
